/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.Bootcamp2020.Java;

public class Main {

    public static void main(String[] args) {

        HelloWorld helloWorld = new HelloWorld();

        helloWorld.hw();
    }
}