/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bootcamp2020.Java;

import Bootcamp2020.Java.Web.CorsHandler;
import Bootcamp2020.Java.Web.Webserver;

public class Main {

    public static void main(String[] args) throws Exception {

        HelloWorld helloWorld = new HelloWorld();

        helloWorld.hw();

        CorsHandler corsHandler = new CorsHandler();

        RockPaperScissors rockPaperScissors = new RockPaperScissors();

        new Webserver(rockPaperScissors, corsHandler).startJetty();
    }
}